### ISSUE TITLE
Remote Event Receiver Guidance

### ISSUE THREAD

**Issue by frankmarasco** [OfficeDev/PnP-Guidance#18]
Add more details on timeouts and best practices for long running operations

**Comment by jansenbe** [comment]
long running remote event receivers are a no-go...what do you think of having the event receiver post a message to a queue and background task which picks it up. Working on timerjob framework that will make this possible (one needs to be able to 'transfer' the calling user's context to the asynchronously running background process).

**Comment by frankmarasco** [comment]
I was  thinking along the lines just needed a place to track this.

**Comment by VesaJuvonen** [comment]
Was also on my blog todo list with details what we have gathered from the feature PMs related on the exact timings and practices. We should have simple story with storage queue and web jobs... and then introduction story to more advance model with the remote timerjob framework. I'd actually write 2 articles... first for the intro, second for the remote timer job framework approach with multithreading support when that's done.

Would suggest following:
Write the generic story - Vesa
Write introduction to framework based code - Bert

Frank can concentrate on the site provisioning framework. Deal?

**Comment by Zimmergren** [comment]
:+1: 
I like the idea Bert is talking about. For what its worth I implemented something similar just the other week where a "job-request" list is populated with "tasks" and then a simple web job is listening to that list every <n> minutes (configurable) and takes care of business.

It works well, but at the same time I think it needs to be robust enough to handle heavy load multiple simultaneous executions without any hiccups (mine doesn't), so for it to be multi-threaded and designed for heavy action is probably a must. 
Just a few thoughts from my end of the pond.

**Comment by VesaJuvonen** [comment]
Thanks Tobias. Process for this one will be exactly the same task feeding approach as with the https://github.com/OfficeDev/PnP/tree/master/Solutions/OD4B.Configuration.Async solution. That was however pretty complex and we need to explain the simplified process, so that field will understand how to truly take advantage of the async queuing process with storage queues and web jobs.

Code exists already, just to write down the story by end of next week should be now the approach. 

We or Bert are pretty far with the multi-threaded approach as well, which was also demonstrated in TechReady this week. Looks really good. Now we just need to concentrate on proper documentation on this model.

**Comment by Zimmergren** [comment]
:+1: Looking forward to seeing the outcome, you guys are doing an awesome job.

**Comment by frankmarasco** [comment]
@VesaJuvonen  concur and agree

**Comment by VesaJuvonen** [comment]
Closing some backlog items - this is nicely explained in following PnP Guidance article - https://github.com/OfficeDev/PnP-Guidance/blob/master/articles/SharePoint-Add-In-Recipe-event-receiver-and-list-event-receiver.md
