### ISSUE TITLE
The object specified does not belong to a list while extracting Project Site Collection Template

### ISSUE THREAD

**Issue by Mani51** [OfficeDev/PnP-Guidance#43]
Hi,

I am extracting office 365 project site collection by using the below powershell script
**Connect-SPOnline
Get-SPOProvisioningTemplate -Out "PnP-Provisioning-File.xml"**
but i am getting below error while extracting the project site collection
**The object specified does not belong to a listGet-SPOProvisioningTemplate : The object specified does not belong to a list.
At line:1 char:1
- Get-SPOProvisioningTemplate -Out "PnP-Provisioning-File.xml"
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], ServerException
  - FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.GetProvisioningTemplate**

Please help me out on this

**Comment by VesaJuvonen** [comment]
Hi Mani51, 
since this is not an issue around the documentation, will close this one from here. There's generally few things to follow around these issues and hopefully you have been able to figure out the issue already.

Generic support - fastest response from PnP Yammer group at http://aka.ms/OfficeDevPnPYammer
If you run into actual issues around the code in PnP engine, would suggest to create an issue to PnP Core component GitHub repository at https://github.com/OfficeDev/PnP-Sites-Core with following details:
- Environment - SharePoint Online / on-premise
- Template details - what site template you were using?
- Anything specific in configurations?

Would anyway start with a discussion at Yammer with the Core team. thx.
