### ISSUE TITLE
Access denied for ctx.ExecuteQuery()

### ISSUE THREAD

**Issue by iandow** [OfficeDev/PnP-Guidance#45]
I'm trying to follow this guide for customizing Sharepoint on O365 with javascript:
https://github.com/OfficeDev/PnP-Guidance/blob/master/articles/Customize-your-SharePoint-site-UI-by-using-JavaScript.md

When I run the Core.EmbedJavascript project, it deploys to my O365 developer site successfully, but after I authorize O365 to trust my app and my browser redirects to

https://localhost:44300/Pages/Default.aspx?SPHostUrl=https%3a%2f%2fiantest123.sharepoint.com&SPLanguage=en-US&SPClientTag=0&SPProductNumber=16.0.5018.1216

I get this error:

```
Server Error in '/' Application.

Access denied. You do not have permission to perform this action or access this resource.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.

```

The entire error listing is here:
http://pastebin.com/73TJvDW7

Does anyone know how to fix this?

Thanks in advance.

**Comment by iandow** [comment]
I sorted this out by uninstalling IIS 10 Express and reinstalling IIS 8 Express. Cheers.

**Comment by biz1a** [comment]
The same, I see this error in almost every sample here. Looks like script link cannot reference to JS file from outside given site collection?

**Comment by VesaJuvonen** [comment]
To be able to run this code, you will need to grant sufficient permissions for the add-in and account which you are using will need to have sufficient permissions as well. In this case you'd have to be at least site owner to be able to execute this code.

Since this is more around making sample to work properly in your environment, would suggest to use the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer for the question. There's more than 4000 other community members in that group assisting actively each other, including multiple MSFTs. 

If the permission check-up does not solve this, would suggest to start discussion in the Yammer group. We are actively using similar setup with tens or hundreds of customers, so we know that the code itself does work. Will close the issue.
